//! `kestrel-gui` — the native desktop frontend of Kestrel (requirements
//! §6, ADR 0001: Slint shell + sandboxed wry body viewport).
//!
//! The Slint event loop owns the main thread (OS requirement); the
//! engine runs on the shared tokio runtime; communication is via the
//! message protocol only (message-protocol §6).
#![cfg_attr(test, allow(clippy::unwrap_used, clippy::expect_used, missing_docs))]

pub mod viewport;

pub use viewport::{CidPart, REQUIRED_CSP, SharedViewportState, ViewportState, wrap_html_with_csp};

/// Slint-generated module (contains unwraps generated by the compiler).
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::pedantic,
    clippy::all,
    warnings
)]
pub mod ui {
    slint::include_modules!();
}
pub use ui::*;
