#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BASELINES_DIR="$REPO_ROOT/benches/baselines"
BENCH_OUTPUT="/tmp/bench-output.txt"

cd "$REPO_ROOT"

echo "Running benchmarks..."
cargo bench --workspace 2>&1 | tee "$BENCH_OUTPUT"

parse_mean_ms() {
  local pattern="$1"
  local line mean_raw unit
  line=$(grep -P "$pattern\\s+time:" "$BENCH_OUTPUT" || true)
  if [ -z "$line" ]; then echo ""; return; fi
  mean_raw=$(echo "$line" | grep -oP 'time:\s+\[\K[0-9.]+')
  unit=$(echo "$line" | grep -oP 'time:\s+\[[0-9.]+\s+\K\S+')
  case "$unit" in
    ns) echo "scale=4; $mean_raw / 1000000" | bc ;;
    us) echo "scale=4; $mean_raw / 1000" | bc ;;
    ms) echo "$mean_raw" ;;
    s)  echo "scale=4; $mean_raw * 1000" | bc ;;
    *)  echo ""; return ;;
  esac
}

write_baseline() {
  local file="$1" benchmark="$2" field="$3" value="$4" thresholds="$5"
  cat > "$file" <<EOF
{
  "benchmark": "$benchmark",
  "$field": $value,
  "thresholds": $thresholds,
  "recorded_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "notes": "Auto-generated by update-baselines.sh"
}
EOF
  echo "Updated $file with $field=$value"
}

# Ingest: convert time (seconds) to msgs/sec (100 msgs / time_sec)
MEAN_SEC=$(grep -oP 'ingest/envelopes_100/batch\s+time:\s+\[\K[0-9.]+' "$BENCH_OUTPUT" | head -1)
if [ -n "$MEAN_SEC" ]; then
  MSGS_PER_SEC=$(echo "scale=2; 100 / $MEAN_SEC" | bc)
  write_baseline "$BASELINES_DIR/ingest.json" \
    "ingest/envelopes_100/batch" "mean_msgs_per_sec" "$MSGS_PER_SEC" \
    '{ "fail_msgs_per_sec": 800, "warn_msgs_per_sec": 1500 }'
fi

# Search 100k
MS=$(parse_mean_ms "search_100k/text_query_first_50")
if [ -n "$MS" ]; then
  write_baseline "$BASELINES_DIR/search_100k.json" \
    "search_100k/text_query_first_50" "mean_ms" "$MS" \
    '{ "fail_ms": 50, "warn_ms": 15 }'
fi

# Search 500k
MS=$(parse_mean_ms "search_500k/text_query_first_50")
if [ -n "$MS" ]; then
  write_baseline "$BASELINES_DIR/search_500k.json" \
    "search_500k/text_query_first_50" "mean_ms" "$MS" \
    '{ "fail_ms": 30 }'
fi

# TUI cold-start
MS=$(parse_mean_ms "tui_cold_start/config_paths_app_state")
if [ -n "$MS" ]; then
  write_baseline "$BASELINES_DIR/tui_cold_start.json" \
    "tui_cold_start/config_paths_app_state" "mean_ms" "$MS" \
    '{ "fail_ms": 150, "warn_ms": 50 }'
fi

# GUI cold-start
MS=$(parse_mean_ms "gui_cold_start/config_paths_viewport_state")
if [ -n "$MS" ]; then
  write_baseline "$BASELINES_DIR/gui_cold_start.json" \
    "gui_cold_start/config_paths_viewport_state" "mean_ms" "$MS" \
    '{ "fail_ms": 500, "warn_ms": 200 }'
fi

# Engine cold-start
MS=$(parse_mean_ms "engine_cold_start/0_accounts")
if [ -n "$MS" ]; then
  write_baseline "$BASELINES_DIR/engine_cold_start.json" \
    "engine_cold_start/0_accounts" "mean_ms" "$MS" \
    '{ "fail_ms": 50 }'
fi

echo "All baselines updated."
